#!/usr/bin/perl
package Splotty::FieldspecManager;

# Splotty::FieldspecManager
#
# Manages the supplemental fieldspec pattern:
#
#   foo.yaml        -- user's hand-crafted main fieldspec
#   foo-supp.yaml   -- auto-generated by splotty (^G save-group, etc.)
#
# On load:  main + supp are merged in memory; neither file is altered.
# On save:  only the supp is written/rewritten (main is never touched).
# Compress: supp is merged into main (with order+flow preserved), backed up,
#           then supp is deleted.  Invoked by:  splotty -f foo.yaml --fs-compress
#
# Exports:
#   fieldspec_supp_path($main_path)                       -> $supp_path
#   load_fieldspec_merged($main_path)                     -> \%merged
#   save_group_to_supp($main_path, $group_name, \@fields) -> $supp_path | die
#   compress_supp_into_main($main_path)                   -> ($ok, $message)

use v5.36;
use utf8;
use Exporter 'import';
use File::Basename  qw(dirname basename);
use File::Spec;
use File::Copy      qw(copy);
use Cwd             qw(abs_path);
use POSIX           qw(strftime);
use YAML::XS        qw(LoadFile);    # plain loads (supp, first-pass main)
use YAML::PP;
use YAML::PP::Common qw(
    PRESERVE_ORDER
    PRESERVE_FLOW_STYLE
    YAML_FLOW_SEQUENCE_STYLE
);

our @EXPORT_OK = qw(
    fieldspec_supp_path
    load_fieldspec_merged
    save_group_to_supp
    compress_supp_into_main
);

our $VERSION = '1.0';

# ---------------------------------------------------------------------------
# Path helpers
# ---------------------------------------------------------------------------

sub fieldspec_supp_path {
    my ($main_path) = @_;
    my $dir  = dirname($main_path);
    my $base = basename($main_path);
    if ($base =~ /\A(.+?)(\.[^.]+)\z/) {
        return File::Spec->catfile($dir, "$1-supp$2");
    }
    return File::Spec->catfile($dir, "$base-supp");
}

sub _backup_path {
    my ($main_path) = @_;
    my $dir  = dirname($main_path);
    my $base = basename($main_path);
    my $ts   = strftime("%Y%m%d-%H%M%S", localtime);
    if ($base =~ /\A(.+?)(\.[^.]+)\z/) {
        return File::Spec->catfile($dir, "$1-orig-$ts$2");
    }
    return File::Spec->catfile($dir, "$base-orig-$ts");
}

# ---------------------------------------------------------------------------
# Internal YAML helpers
# ---------------------------------------------------------------------------

# Load with YAML::XS (plain hashes/arrays – used for supp and for the
# splotty runtime which expects plain structures).
sub _load_plain {
    my ($path) = @_;
    return {} unless -f $path;
    my $data = eval { LoadFile($path) };
    warn "FieldspecManager: failed to load '$path': $@\n" if $@;
    return $data // {};
}

# Load with YAML::PP preserving document order and flow/block style.
# Returns YAML::PP tied structures – only used for compress.
sub _load_preserve {
    my ($path) = @_;
    return {} unless -f $path;
    my $yp   = _yp_preserve();
    my $data = eval { $yp->load_file($path) };
    warn "FieldspecManager: failed to load '$path': $@\n" if $@;
    return $data // {};
}

sub _yp_preserve {
    YAML::PP->new(preserve => PRESERVE_ORDER | PRESERVE_FLOW_STYLE);
}

# ---------------------------------------------------------------------------
# Merge logic (shared between load_fieldspec_merged and compress)
# ---------------------------------------------------------------------------

# Merge supp data into $main in-place.
# $make_flow_seq: optional coderef($arrayref) -> flow-style node.
#   Used during compress so newly-added group arrays get flow style.
#   Pass undef for plain-hashref merges (runtime load).
sub _merge_supp_into {
    my ($main, $supp, $make_flow_seq) = @_;

    # --- groups section ---
    if ($supp->{groups} && %{$supp->{groups}}) {
        $main->{groups} //= {};
        for my $gname (keys %{$supp->{groups}}) {
            # Don't stomp an existing group's key/state
            $main->{groups}{$gname} //= $supp->{groups}{$gname};
        }
    }

    # --- fields section ---
    if ($supp->{fields} && %{$supp->{fields}}) {
        $main->{fields} //= {};
        for my $fname (keys %{$supp->{fields}}) {
            my @supp_groups = @{ $supp->{fields}{$fname}{groups} // [] };
            next unless @supp_groups;

            $main->{fields}{$fname} //= {};
            my $mf = $main->{fields}{$fname};

            if (!exists $mf->{groups}) {
                # Brand-new field in main: create array (flow if possible)
                my $arr = $make_flow_seq ? $make_flow_seq->(\@supp_groups)
                                         : [@supp_groups];
                $mf->{groups} = $arr;
            } else {
                # Existing field: append missing group names.
                # YAML::PP tied arrays keep their flow-style flag when pushed.
                my $existing = $mf->{groups};
                my %seen = map { $_ => 1 } @$existing;
                for my $g (@supp_groups) {
                    push @$existing, $g unless $seen{$g}++;
                }
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

# Load the main fieldspec and, if a supp file exists, merge it in.
# Returns a plain hashref (YAML::XS style) suitable for splotty's runtime.
sub load_fieldspec_merged {
    my ($main_path) = @_;

    my $main      = _load_plain($main_path);
    my $supp_path = fieldspec_supp_path($main_path);

    if (-f $supp_path) {
        my $supp = _load_plain($supp_path);
        _merge_supp_into($main, $supp, undef);  # plain arrays, no flow wrapping
    }

    return $main;
}

# Save a new group (and its field memberships) to the supp file.
# Reloads the existing supp first so concurrent saves don't clobber each other.
# Dies on error; returns $supp_path on success.
sub save_group_to_supp {
    my ($main_path, $group_name, $field_names) = @_;

    die "save_group_to_supp: group_name is required\n"
        unless defined $group_name && length $group_name;
    die "save_group_to_supp: field_names must be an arrayref\n"
        unless ref $field_names eq 'ARRAY';

    my $supp_path = fieldspec_supp_path($main_path);

    # Reload supp each time to pick up concurrent changes
    my $supp = -f $supp_path ? _load_plain($supp_path) : {};
    $supp->{groups} //= {};
    $supp->{fields} //= {};

    # Register the group (preserve existing key/state if already there)
    $supp->{groups}{$group_name} //= { key => 'auto', state => 1 };

    # Add group membership to each field
    for my $fname (@$field_names) {
        $supp->{fields}{$fname} //= { groups => [] };
        my $grps = $supp->{fields}{$fname}{groups} //= [];
        push @$grps, $group_name
            unless grep { $_ eq $group_name } @$grps;
    }

    _write_supp($supp_path, $supp);   # dies on error
    return $supp_path;
}

# Merge supp into main, preserving document order and flow-style arrays.
#   - Backs up main to a timestamped -orig file before touching it.
#   - New group arrays in main will be written as flow sequences.
#   - Existing flow arrays (e.g. groups: [All, X]) stay flow; new names
#     appended to them will be included in the flow output because YAML::PP
#     tied arrays track their container style.
#   - Deletes supp on success.
# Returns ($ok_bool, $message_string).
sub compress_supp_into_main {
    my ($main_path) = @_;

    $main_path = abs_path($main_path) // $main_path;

    return (0, "Main fieldspec not found: $main_path")
        unless -f $main_path;

    my $supp_path = fieldspec_supp_path($main_path);
    return (0, "No supplemental file found at: $supp_path\n"
             . "Nothing to compress.")
        unless -f $supp_path;

    # --- backup ---
    my $backup = _backup_path($main_path);
    copy($main_path, $backup)
        or return (0, "Failed to back up '$main_path' → '$backup': $!");

    # --- load main with style preservation ---
    my $yp   = _yp_preserve();
    my $main = eval { $yp->load_file($main_path) };
    if ($@) {
        return (0, "Failed to load '$main_path' with YAML::PP: $@");
    }

    # --- load supp plain ---
    my $supp = _load_plain($supp_path);

    # --- merge with flow-style factory for new group arrays ---
    my $make_flow = sub {
        my ($items) = @_;
        return $yp->preserved_sequence(
            [@$items],
            style => YAML_FLOW_SEQUENCE_STYLE,
        );
    };
    _merge_supp_into($main, $supp, $make_flow);

    # --- write merged main (preserves existing order + flow) ---
    eval { $yp->dump_file($main_path, $main) };
    if ($@) {
        # attempt rollback
        copy($backup, $main_path);
        return (0, "Failed to write merged '$main_path': $@\n(restored from backup)");
    }

    # --- remove supp ---
    unlink $supp_path
        or warn "FieldspecManager: could not delete '$supp_path': $!\n";

    return (1, "Merged '$supp_path' → '$main_path'\nBackup: '$backup'");
}

# ---------------------------------------------------------------------------
# Supp file writer
# ---------------------------------------------------------------------------
# Writes a clean, minimal YAML with flow-style groups arrays.
# The structure is simple enough that we emit it directly rather than
# going through a YAML serialiser (avoids YAML::PP tied-node complexity
# for a write-only file we fully control).

sub _write_supp {
    my ($path, $data) = @_;

    open my $fh, '>', $path
        or die "FieldspecManager: cannot write '$path': $!\n";
    binmode $fh, ':encoding(UTF-8)';

    say $fh "# splotty supplemental fieldspec (auto-generated -- do not hand-edit lightly)";
    say $fh "# Merge into your main fieldspec with:  splotty -f YOURFILE.yaml --fs-compress";
    say $fh "---";

    if ($data->{groups} && %{$data->{groups}}) {
        say $fh "groups:";
        for my $gname (sort keys %{$data->{groups}}) {
            my $g     = $data->{groups}{$gname};
            my $key   = $g->{key}   // 'auto';
            my $state = $g->{state} ? 1 : 0;
            say $fh "  $gname:";
            say $fh "    key: $key";
            say $fh "    state: $state";
        }
    }

    if ($data->{fields} && %{$data->{fields}}) {
        say $fh "fields:";
        for my $fname (sort keys %{$data->{fields}}) {
            my @grps = @{ $data->{fields}{$fname}{groups} // [] };
            say $fh "  $fname:";
            if (@grps) {
                my $gstr = join(', ', @grps);
                say $fh "    groups: [$gstr]";
            }
        }
    }

    close $fh;
}

1;

__END__

=head1 NAME

Splotty::FieldspecManager - Supplemental fieldspec management for splotty

=head1 SYNOPSIS

    use Splotty::FieldspecManager qw(
        fieldspec_supp_path
        load_fieldspec_merged
        save_group_to_supp
        compress_supp_into_main
    );

    # Load main + any supp into a plain hashref
    my $merged = load_fieldspec_merged('fields.yaml');

    # Save a new group to the supp file (never touches fields.yaml)
    save_group_to_supp('fields.yaml', 'MyGroup', [qw(pt.avg pt.ewma pt.min)]);

    # Merge supp into main (preserves order + flow style), then delete supp
    my ($ok, $msg) = compress_supp_into_main('fields.yaml');

=head1 DESCRIPTION

Implements a two-file fieldspec pattern for splotty:

=over 4

=item B<foo.yaml> — hand-crafted by the user; B<never written by splotty>

=item B<foo-supp.yaml> — auto-generated by splotty features such as C<^G>

=back

On startup, if both files exist they are merged in memory.  The supp file is
reloaded and rewritten atomically on each C<save_group_to_supp> call so that
concurrent splotty instances don't stomp each other.

C<compress_supp_into_main> merges the supp into the main file using
L<YAML::PP> with C<PRESERVE_ORDER | PRESERVE_FLOW_STYLE>, so existing
C<groups: [All, X]> arrays stay inline.  Newly added group arrays are also
written as flow sequences.  The original main file is backed up to a
timestamped C<-orig> file before anything is changed.

=head1 FUNCTIONS

=head2 fieldspec_supp_path($main_path)

Returns the derived path for the supplemental file
(C<foo.yaml> → C<foo-supp.yaml>).

=head2 load_fieldspec_merged($main_path)

Loads the main fieldspec with L<YAML::XS> and, if a supp file exists, merges
its C<groups> and C<fields.*.groups> entries in.  Returns a plain hashref.

=head2 save_group_to_supp($main_path, $group_name, \@field_names)

Reloads the current supp (if any), adds C<$group_name> to the groups section
and appends it to each named field's groups list, then writes the supp back.
Dies on I/O error.  Returns the supp path on success.

=head2 compress_supp_into_main($main_path)

Merges the supp into the main file with style preservation, backs up the
original, and deletes the supp.  Returns C<($ok, $message)>.

=cut
